version: '>= 0.14.0'

formatter: markdown table

content: |-
  # Easy IMM - Profiles Only example for Intersight

  This example is part of the Cisco [*Easy IMM*](https://cisco.com/go/easy-imm) project. Its goal is to allow users to instantiate Infrastrcture in minutes using an easy to use, opinionated data model. It takes away the complexity of having to deal with references, dependencies or loops. By completely separating data (defining variables) from logic (infrastructure declaration), it allows the user to focus on describing the intended configuration while using a set of maintained and tested Terraform Modules without the need to understand the low-level Intersight object model. More information can be found here: <https://cisco.com/go/easy-imm>.

  ## Environment Variables

  ### Terraform Cloud/Enterprise - Workspace Variables
  - Add variable apikey with the value of [your-api-key]
  - Add variable secretkey with the value of [your-secret-file-content]

  ### Linux and Windows
  ```bash
  export TF_VAR_apikey="<your-api-key>"
  export TF_VAR_secretkeyfile="<secret-key-file-location>"
  ```

  {{ .Requirements }}
  {{ .Providers }}
  {{ .Inputs }}
  {{ .Outputs }}
  {{ .Resources }}
output:
  file: README.md
  mode: replace

sort:
  enabled: false